---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: congressedits.bot
  namespace: congressedits
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: congressedits.bot
    spec:
      containers:
        - name: bot
          image: docker-registry.tools.wmflabs.org/toollabs-nodejs-base:latest
          command: ["/data/project/congressedits/bin/congressedits", "run"]
          workingDir: /data/project/congressedits
          env:
            - name: HOME
              value: /data/project/congressedits
          imagePullPolicy: Always
          volumeMounts:
            - name: home
              mountPath: /data/project/congressedits
      volumes:
        - name: home
          hostPath:
            path: /data/project/congressedits

